services:
  app:
    container_name: smart-shell-springboot
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_HOST: $SMART_SHELL_POSTGRES_HOST
        POSTGRES_PORT: $SMART_SHELL_POSTGRES_PORT
        POSTGRES_DATABASE: $SMART_SHELL_POSTGRES_DATABASE
        POSTGRES_USERNAME: $SMART_SHELL_POSTGRES_USERNAME
        POSTGRES_PASSWORD: $SMART_SHELL_POSTGRES_PASSWORD
        MONGO_HOST: $SMART_SHELL_MONGO_HOST
        MONGO_PORT: $SMART_SHELL_MONGO_PORT
        MONGO_DATABASE: $SMART_SHELL_MONGO_DATABASE
        MONGO_USERNAME: $SMART_SHELL_MONGO_USERNAME
        MONGO_PASSWORD: $SMART_SHELL_MONGO_PASSWORD
        REDIS_HOST: $SMART_SHELL_REDIS_HOST
        REDIS_PORT: $SMART_SHELL_REDIS_PORT
        REDIS_USERNAME: $SMART_SHELL_REDIS_USERNAME
        REDIS_PASSWORD: $SMART_SHELL_REDIS_PASSWORD
    environment:
      POSTGRES_HOST: $SMART_SHELL_POSTGRES_HOST
      POSTGRES_PORT: $SMART_SHELL_POSTGRES_PORT
      POSTGRES_DATABASE: $SMART_SHELL_POSTGRES_DATABASE
      POSTGRES_USERNAME: $SMART_SHELL_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $SMART_SHELL_POSTGRES_PASSWORD
      MONGO_HOST: $SMART_SHELL_MONGO_HOST
      MONGO_PORT: $SMART_SHELL_MONGO_PORT
      MONGO_DATABASE: $SMART_SHELL_MONGO_DATABASE
      MONGO_USERNAME: $SMART_SHELL_MONGO_USERNAME
      MONGO_PASSWORD: $SMART_SHELL_MONGO_PASSWORD
      REDIS_HOST: $SMART_SHELL_REDIS_HOST
      REDIS_PORT: $SMART_SHELL_REDIS_PORT
      REDIS_USERNAME: $SMART_SHELL_REDIS_USERNAME
      REDIS_PASSWORD: $SMART_SHELL_REDIS_PASSWORD
    ports:
      - "${SMART_SHELL_SPRINGBOOT_PORT}:8081"
    networks:
      - smart-shell-net
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true