services:
  app:
    container_name: smart-shell-springboot
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_HOST: $POSTGRES_HOST
        POSTGRES_PORT: $POSTGRES_PORT
        POSTGRES_DATABASE: $POSTGRES_DATABASE
        POSTGRES_USERNAME: $POSTGRES_USERNAME
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        MONGO_HOST: $MONGO_HOST
        MONGO_PORT: $MONGO_PORT
        MONGO_DATABASE: $MONGO_DATABASE
        MONGO_USERNAME: $MONGO_USERNAME
        MONGO_PASSWORD: $MONGO_PASSWORD
        REDIS_HOST: $REDIS_HOST
        REDIS_PORT: $REDIS_PORT
        REDIS_USERNAME: $REDIS_USERNAME
        REDIS_PASSWORD: $REDIS_PASSWORD
        KEYSTORE_FILE: $KEYSTORE_FILE
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEYSTORE_DOMAIN: $KEYSTORE_DOMAIN
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      MONGO_HOST: $MONGO_HOST
      MONGO_PORT: $MONGO_PORT
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_USERNAME: $REDIS_USERNAME
      REDIS_PASSWORD: $REDIS_PASSWORD
      KEYSTORE_FILE: $KEYSTORE_FILE
      KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
      KEYSTORE_DOMAIN: $KEYSTORE_DOMAIN
    ports:
      - "8081:8081"
    networks:
      - smart-shell-net  # Conexión a la red smart-shell-net

networks:
  smart-shell-net:  # Definición de la red smart-shell-net
    external: true   # Indicador de que la red ya está creada externamente
